markdown: kramdown
title: Privacy Program
description: Helping you plan for and mitigate privacy risks
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- README.md
- go

permalink: pretty
highlighter: rouge
kramdown:
  auto_ids: true

sass:
  style: :compressed

github:
  organization: 18F
  repository: insite-privacy
  default_branch: 18f-pages

collections:
  pages:
    output: true
    permalink: /:path/

generate_nodes: true
flat_namespace: true

gems:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Navigation
# List links that should appear in the site sidebar here
navigation:

repos:
- name: Privacy Program
  description: Main repository
  url: https://github.com/18F/insite-privacy


# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true
  placeholder: Search
  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
